import { KeyValueType } from './type';

export const FORM_NAMES: KeyValueType = {
  'deoxys-attack': '테오키스-어택폼',
  'deoxys-defense': '테오키스-디펜스폼',
  'deoxys-speed': '테오키스-스피드폼',
  'wormadam-sandy': '모래땅도롱',
  'wormadam-trash': '슈레도롱',
  'shaymin-sky': '쉐이미-스카이폼',
  'giratina-origin': '기라티나-오리진폼',
  'rotom-heat': '히트로토무',
  'rotom-wash': '워시로토무',
  'rotom-frost': '프로스트로토무',
  'rotom-fan': '스핀로토무',
  'rotom-mow': '커트로토무',
  'castform-sunny': '캐스퐁-태양의 모습',
  'castform-rainy': '캐스퐁-빗방울의 모습',
  'castform-snowy': '캐스퐁-설운의 모습',
  'basculin-blue-striped': '배쓰나이-청색근의 모습',
  'darmanitan-zen': '불비달마-달마모드',
  'meloetta-pirouette': '메로엣타-스텝폼',
  'tornadus-therian': '토네로스-영물폼',
  'thundurus-therian': '볼트로스-영물폼',
  'landorus-therian': '랜드로스-영물폼',
  'kyurem-black': '블랙큐레무',
  'kyurem-white': '화이트큐레무',
  'keldeo-resolute': '케르디오-각오의 모습',
  'meowstic-female': '냐오닉스-암컷',
  'aegislash-blade': '킬가르도-블레이드폼',
  'pumpkaboo-small': '호바귀-작은 사이즈',
  'pumpkaboo-large': '호바귀-큰 사이즈',
  'pumpkaboo-super': '호바귀-특대 사이즈',
  'gourgeist-small': '펌킨인-작은 사이즈',
  'gourgeist-large': '펌킨인-큰 사이즈',
  'gourgeist-super': '펌킨인-특대 사이즈',
  'kyogre-primal': '원시가이오가',
  'groudon-primal': '원시그란돈',
  'pikachu-rock-star': '하드록',
  'pikachu-belle': '마담',
  'pikachu-pop-star': '아이돌',
  'pikachu-phd': '닥터',
  'pikachu-libre': '마스크드',
  'pikachu-cosplay': '코스플레이',
  'hoopa-unbound': '굴레를 벗어난 후파',
  'pikachu-original-cap': '오리지널캡',
  'pikachu-hoenn-cap': '호연캡',
  'pikachu-sinnoh-cap': '신오캡',
  'pikachu-unova-cap': '하나캡',
  'pikachu-kalos-cap': '칼로스캡',
  'pikachu-alola-cap': '알로라캡',
  'greninja-battle-bond': '개굴닌자-유대변화',
  'greninja-ash': '지우개굴닌자',
  'zygarde-10-power-construct': '지가르데-10%폼',
  'zygarde-50-power-construct': '지가르데-50%폼',
  'zygarde-complete': '지가르데-퍼펙트폼',
  'oricorio-pom-pom': '춤추새-파칙파칙스타일',
  'oricorio-pau': '춤추새-훌라훌라스타일',
  'oricorio-sensu': '춤추새-하늘하늘스타일',
  'lycanroc-midnight': '루가루암-한밤중의 모습',
  'wishiwashi-school': '약어리-군집의 모습',
  'minior-red': '메테노-코어',
  'mimikyu-busted': '따라큐-들킨 모습',
  'magearna-original': '마기아나-500년 전의 색',
  'pikachu-partner-cap': '너로정했다캡',
  'lycanroc-dusk': '루가루암-황혼의 모습',
  'necrozma-dusk': '네크로즈마-황혼의 갈기',
  'necrozma-dawn': '네크로즈마-새벽의 날개',
  'necrozma-ultra': '울트라네크로즈마',
  'pikachu-starter': '파트너',
  'eevee-starter': '파트너',
  'pikachu-world-cap': '월드캡',
  'cramorant-gulping': '윽우지-그대로 삼킨 모습',
  'cramorant-gorging': '윽우지-통째로 삼킨 모습',
  'toxtricity-low-key': '스트린더-로우한 모습',
  'eiscue-noice': '빙큐보-나이스페이스',
  'indeedee-female': '에써르-암컷',
  'morpeko-hangry': '모르페코-배고픈 모양',
  'zacian-crowned': '자시안-검왕',
  'zamazenta-crowned': '자마젠타-방패왕',
  'eternatus-eternamax': '무한다이노-무한다이맥스',
  'urshifu-rapid-strike': '우라오스-연격의 태세',
  'zarude-dada': '자루도-아빠',
  'calyrex-ice': '버드렉스-백마 탄 모습',
  'calyrex-shadow': '버드렉스-흑마 탄 모습',
  'dialga-origin': '디아루가-오리진폼',
  'palkia-origin': '펄기아-오리진폼',
  'basculin-white-striped': '배쓰나이-백색근의 모습',
  'basculegion-female': '대쓰여너-암컷',
  'enamorus-therian': '러브로스-영물폼',
  'tauros-paldea-combat-breed': '켄타로스-팔데아-컴뱃',
  'tauros-paldea-blaze-breed': '켄타로스-팔데아-블레이즈',
  'tauros-paldea-aqua-breed': '켄타로스-팔데아-워터',
  'wooper-paldea': '우파-팔데아',
  'oinkologne-female': '퍼퓨돈-암컷',
  'dudunsparce-three-segment': '노고고치-세 마디 폼',
  'palafin-hero': '돌핀맨-마이티폼',
  'squawkabilly-blue-plumage': '시비꼬-블루 페더',
  'squawkabilly-yellow-plumage': '시비꼬-옐로 페더',
  'squawkabilly-white-plumage': '시비꼬-화이트 페더',
  'gimmighoul-roaming': '모으령-도주폼',
  'ursaluna-bloodmoon': '다투곰-붉은 달',
  'ogerpon-wellspring-mask': '오거폰-우물의가면',
  'ogerpon-hearthflame-mask': '오거폰-화덕의가면',
  'ogerpon-cornerstone-mask': '오거폰-주춧돌의가면',
  'venusaur-mega': '메가이상해꽃',
  'charizard-mega-x': '메가리자몽X',
  'charizard-mega-y': '메가리자몽Y',
  'blastoise-mega': '메가거북왕',
  'alakazam-mega': '메가후딘',
  'gengar-mega': '메가팬텀',
  'kangaskhan-mega': '메가캥카',
  'pinsir-mega': '메가쁘사이저',
  'gyarados-mega': '메가갸라도스',
  'aerodactyl-mega': '메가프테라',
  'mewtwo-mega-x': '메가뮤츠X',
  'mewtwo-mega-y': '메가뮤츠Y',
  'ampharos-mega': '메가전룡',
  'scizor-mega': '메가핫삼',
  'heracross-mega': '메가헤라크로스',
  'houndoom-mega': '메가헬가',
  'tyranitar-mega': '메가마기라스',
  'blaziken-mega': '메가번치코',
  'gardevoir-mega': '메가가디안',
  'mawile-mega': '메가입치트',
  'aggron-mega': '메가보스로라',
  'medicham-mega': '메가요가램',
  'manectric-mega': '메가썬더볼트',
  'banette-mega': '메가다크펫',
  'absol-mega': '메가앱솔',
  'garchomp-mega': '메가한카리아스',
  'lucario-mega': '메가루카리오',
  'abomasnow-mega': '메가눈설왕',
  'floette-eternal': '영원의 꽃',
  'latias-mega': '메가라티아스',
  'latios-mega': '메가라티오스',
  'swampert-mega': '메가대짱이',
  'sceptile-mega': '메가나무킹',
  'sableye-mega': '메가깜까미',
  'altaria-mega': '메가파비코리',
  'gallade-mega': '메가엘레이드',
  'audino-mega': '메가다부니',
  'sharpedo-mega': '메가샤크니아',
  'slowbro-mega': '메가야도란',
  'steelix-mega': '메가강철톤',
  'pidgeot-mega': '메가피죤투',
  'glalie-mega': '메가얼음귀신',
  'diancie-mega': '메가디안시',
  'metagross-mega': '메가메타그로스',
  'rayquaza-mega': '메가레쿠쟈',
  'camerupt-mega': '메가폭타',
  'lopunny-mega': '메가이어롭',
  'salamence-mega': '메가보만다',
  'beedrill-mega': '메가독침붕',
  'raichu-alola': '라이츄-알로라',
  'sandshrew-alola': '모래두지-알로라',
  'sandslash-alola': '고지-알로라',
  'vulpix-alola': '식스테일-알로라',
  'ninetales-alola': '나인테일-알로라',
  'diglett-alola': '디그다-알로라',
  'dugtrio-alola': '닥트리오-알로라',
  'meowth-alola': '나옹-알로라',
  'persian-alola': '페르시온-알로라',
  'geodude-alola': '꼬마돌-알로라',
  'graveler-alola': '데구리-알로라',
  'golem-alola': '딱구리-알로라',
  'grimer-alola': '질퍽이-알로라',
  'muk-alola': '질뻐기-알로라',
  'exeggutor-alola': '나시-알로라',
  'marowak-alola': '텅구리-알로라',
  'rattata-alola': '꼬렛-알로라',
  'raticate-alola': '레트라-알로라',
  'meowth-galar': '나옹-가라르',
  'ponyta-galar': '포니타-가라르',
  'rapidash-galar': '날쌩마-가라르',
  'slowpoke-galar': '야돈-가라르',
  'slowbro-galar': '야도란-가라르',
  'farfetchd-galar': '파오리-가라르',
  'weezing-galar': '또도가스-가라르',
  'mr-mime-galar': '마임맨-가라르',
  'articuno-galar': '프리져-가라르',
  'zapdos-galar': '썬더-가라르',
  'moltres-galar': '파이어-가라르',
  'slowking-galar': '야도킹-가라르',
  'corsola-galar': '코산호-가라르',
  'zigzagoon-galar': '지그제구리-가라르',
  'linoone-galar': '직구리-가라르',
  'darumaka-galar': '달막화-가라르',
  'darmanitan-galar-standard': '불비달마-가라르-노말모드',
  'yamask-galar': '데스마스-가라르',
  'stunfisk-galar': '메더-가라르',
  'darmanitan-galar-zen': '불비달마-가라르-달마모드',
  'growlithe-hisui': '가디-히스이',
  'arcanine-hisui': '윈디-히스이',
  'voltorb-hisui': '찌리리공-히스이',
  'electrode-hisui': '붐볼-히스이',
  'typhlosion-hisui': '블레이범-히스이',
  'qwilfish-hisui': '침바루-히스이',
  'sneasel-hisui': '날쌩마-히스이',
  'samurott-hisui': '다이켄키-히스이',
  'lilligant-hisui': '드레디어-히스이',
  'zorua-hisui': '조로아-히스이',
  'zoroark-hisui': '조로아크-히스이',
  'braviary-hisui': '워글-히스이',
  'sliggoo-hisui': '미끄메라-히스이',
  'goodra-hisui': '미끄네일-히스이',
  'avalugg-hisui': '크레베이스-히스이',
  'decidueye-hisui': '모크나이퍼-히스이',
  'venusaur-gmax': '이상해꽃-거다이맥스',
  'charizard-gmax': '리자몽-거다이맥스',
  'blastoise-gmax': '거북왕-거다이맥스',
  'butterfree-gmax': '버터플-거다이맥스',
  'pikachu-gmax': '피카츄-거다이맥스',
  'meowth-gmax': '나옹-거다이맥스',
  'machamp-gmax': '괴력몬-거다이맥스',
  'gengar-gmax': '팬텀-거다이맥스',
  'kingler-gmax': '킹크랩-거다이맥스',
  'lapras-gmax': '라프라스-거다이맥스',
  'eevee-gmax': '이브이-거다이맥스',
  'snorlax-gmax': '잠만보-거다이맥스',
  'garbodor-gmax': '더스트나-거다이맥스',
  'melmetal-gmax': '멜메탈-거다이맥스',
  'rillaboom-gmax': '럼버레오-거다이맥스',
  'cinderace-gmax': '에이스번-거다이맥스',
  'inteleon-gmax': '인텔리레온-거다이맥스',
  'corviknight-gmax': '아머까오-거다이맥스',
  'orbeetle-gmax': '이올브-거다이맥스',
  'drednaw-gmax': '갈가부기-거다이맥스',
  'coalossal-gmax': '석탄산-거다이맥스',
  'flapple-gmax': '사과르-거다이맥스',
  'appletun-gmax': '애프룡-거다이맥스',
  'sandaconda-gmax': '사다이사-거다이맥스',
  'toxtricity-amped-gmax': '스트린더-거다이맥스-하이',
  'centiskorch-gmax': '염뱀장-거다이맥스',
  'hatterene-gmax': '브리무음-거다이맥스',
  'grimmsnarl-gmax': '오롱털-거다이맥스',
  'alcremie-gmax': '마휘핑-거다이맥스',
  'copperajah-gmax': '대왕팬-거다이맥스',
  'duraludon-gmax': '두랄루돈-거다이맥스',
  'urshifu-single-strike-gmax': '우라오스-일격의 태세-거다이맥스',
  'urshifu-rapid-strike-gmax': '우라오스-연격의 태세-거다이맥스',
  'toxtricity-low-key-gmax': '스트린더-거다이맥스-로우',
  'tatsugiri-droopy': '싸리용-늘어진 모습',
  'tatsugiri-stretchy': '싸리용-뻗은 모습',
};
